name: BuildAndUpload
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
jobs:
  release-tag:
    name: Set tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Set up Git
      run: |
        git config --local user.name "${GITHUB_ACTOR}"
        git config --local user.email "${GITHUB_ACTOR}@users.noreply.github.com"
    - name: Bump tag if necessary
      uses: smlx/ccv@v0.10.0
