name: BuildAndUpload
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
jobs:
  release-tag:
    name: Set tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Bump tag if necessary
      uses: smlx/ccv@7318e2f25a52dcd550e75384b84983973251a1f8 # v0.10.0
