name: BuildAndUpload
on:
  push:
    branches:
      - main
    tags:
      - v*.*.*
jobs:
  release-tag:
    name: Set tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          noVersionBumpBehavior: patch
      - name: Create tag
        run: |
            git tag ${{ steps.semver.outputs.next }}
            git push origin ${{ steps.semver.outputs.next }}
      # - name: Bump version
      #   uses: anothrNick/github-tag-action@v1
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: true
